/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Path;
import java.nio.file.Paths;


public class App {

    public static void demoOCFL() {
        Path rootPath = Paths.get("storage/root");
        Path workPath = Paths.get("storage/work");
        Path stagingPath = Paths.get("storage/staging");
        String firstId = "1";

        User user = new User("testuser", "test@example.edu");

        RepositoryService repoService = new RepositoryService(rootPath, workPath);
        if (repoService.hasObject(firstId)) {
            repoService.deleteObject(firstId);
        }

        repoService.createObject(firstId, Paths.get(stagingPath.toString(), "/input/1"), user, "Initial version.");
        repoService.deleteObjectFile(firstId, "b.txt", user, "Delete b.");
        repoService.updateObjectFile(
            firstId,
            Paths.get(stagingPath.toString(), "/input/new_files/v3-a/a.txt"),
            "",
            user,
            "Replace a."
        );

        repoService.readObject(firstId, Paths.get("storage/staging/output/1"));
    }

    public static void main(String[] args) {
        System.out.println("Working directory: " + System.getProperty("user.dir"));
        demoOCFL();
    }
}
