/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.nio.file.Path;
import java.nio.file.Paths;


public class App {

    public static void demoOCFL() {
        Path rootPath = Paths.get("storage/root");
        Path workPath = Paths.get("storage/work");
    
        RepositoryService repoService = new RepositoryService(rootPath, workPath);

        String firstId = "1";

        repoService.createObject(firstId, Paths.get("storage/staging/input/1"), "Initial version.");

        repoService.readObject(firstId, Paths.get("storage/staging/output/1"));

    }

    public static void main(String[] args) {
        System.out.println("Working directory: " + System.getProperty("user.dir"));
        demoOCFL();
    }
}
